<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Srinath" name="login_TestCase_TC1.0" tests="5" failures="1" timestamp="28 Jun 2022 18:54:15 GMT" time="15.775" errors="0">
  <testcase name="login_with_validation" time="4.555" classname="com.mln.login.Login_Validation"/>
  <testcase name="login_with_validation" time="1.584" classname="com.mln.login.Login_Validation"/>
  <testcase name="login_with_validation" time="1.651" classname="com.mln.login.Login_Validation"/>
  <testcase name="login_with_validation" time="1.543" classname="com.mln.login.Login_Validation">
    <failure type="java.lang.AssertionError" message="expected [http://automationpractice.com/index.php?controller=my-account] but found [http://automationpractice.com/index.php?controller=authentication]">
      <![CDATA[java.lang.AssertionError: expected [http://automationpractice.com/index.php?controller=my-account] but found [http://automationpractice.com/index.php?controller=authentication]
	at com.mln.login.Login_Validation.login_with_validation(Login_Validation.java:118)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- login_with_validation -->
  <testcase name="login_with_validation" time="2.175" classname="com.mln.login.Login_Validation"/>
</testsuite> <!-- login_TestCase_TC1.0 -->
